import React from "react";
import { nanoid } from "nanoid";
import RenderInput from "../../../components/RenderInput/RenderInput";

const AddItem = ({ formik }) => {
  const inputField = [
    {
      id: nanoid(),
      name: "name",
      label: "Name",
      type: "text",
      required: true,
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },

    {
      id: nanoid(),
      name: "costPrice",
      label: "Cost Price",
      type: "text",
      required: true,
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "markedPrice",
      label: "Marked Price",
      type: "text",
      required: true,
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "sellingPrice",
      label: "Selling Price",
      type: "text",
      required: true,
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "type",
      label: "Type",
      type: "dropDown",
      required: true,
      options: [
        { value: "BEVERAGE", label: "Beverage", id: nanoid() },
        { value: "FOOD", label: "Food", id: nanoid() },
        { value: "CLOTHING", label: "Clothing", id: nanoid() },
      ],
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "tags",
      label: "Tags",
      type: "text",
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "color",
      label: "Color",
      type: "text",
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "stockCount",
      label: "Stock Count",
      type: "number",
      // required: true,
      xs: 12,
      md: 6,
      lg: 6,
      sm: 12,
    },
    {
      id: nanoid(),
      name: "description",
      label: "Description",
      placeholder: "Enter description...",
      type: "richText",
      multiline: true,
      rows: 10,
      required: true,
      md: 12,
      sm: 12,
      xs: 12,
      lg: 12,
    },
  ];
  return <RenderInput inputField={inputField} formik={formik} />;
};

export default AddItem;
